### ISSUE TITLE
'ToBoolean' has been explicitly marked deprecated here

### ISSUE THREAD

**Issue by kierancrowntrt** [lohanidamodar/RNLauncher#3]
Hi I'm unable to build this project in Mac OS X 10.15.3 due to:
`'ToBoolean' has been explicitly marked deprecated here`

**Comment by lohanidamodar** [comment]
Hi, thank you for your effort. As this project was created for demo purpose only. I haven't upgraded. If you do find you can fix, Pull requests are welcome.
